// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxFIXvJDSWiYWKr71k5ZjivOwRv3HtA44',
    appId: '1:654500904802:web:69e0926ab9f75c2523f63b',
    messagingSenderId: '654500904802',
    projectId: 'ieee-fsb-hr-project',
    authDomain: 'ieee-fsb-hr-project.firebaseapp.com',
    storageBucket: 'ieee-fsb-hr-project.appspot.com',
    measurementId: 'G-CXDN3SPMXZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVS0maQD7sq2GCWwMQtZVlI-AutauXY3E',
    appId: '1:654500904802:android:291bb3d18d16d6a223f63b',
    messagingSenderId: '654500904802',
    projectId: 'ieee-fsb-hr-project',
    storageBucket: 'ieee-fsb-hr-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa0OjX-81IapPoo58B7LbpsTH2KvMZdTs',
    appId: '1:654500904802:ios:3c4b2c035eaf909d23f63b',
    messagingSenderId: '654500904802',
    projectId: 'ieee-fsb-hr-project',
    storageBucket: 'ieee-fsb-hr-project.appspot.com',
    androidClientId: '654500904802-odudt3uu494vatcg235uh04n4ud9nqp6.apps.googleusercontent.com',
    iosClientId: '654500904802-kgnbu2io4e5t15d3m3cdu1e1lcf17vf4.apps.googleusercontent.com',
    iosBundleId: 'com.example.ieeeFsbHr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa0OjX-81IapPoo58B7LbpsTH2KvMZdTs',
    appId: '1:654500904802:ios:2ad8a9e5afc5d90d23f63b',
    messagingSenderId: '654500904802',
    projectId: 'ieee-fsb-hr-project',
    storageBucket: 'ieee-fsb-hr-project.appspot.com',
    androidClientId: '654500904802-odudt3uu494vatcg235uh04n4ud9nqp6.apps.googleusercontent.com',
    iosClientId: '654500904802-kn64qp96fgtn67dqesvrd9n5gled4u79.apps.googleusercontent.com',
    iosBundleId: 'com.example.ieeeFsbHr.RunnerTests',
  );
}
